### ISSUE TITLE
Header megamenu drilldown mobile

### ISSUE THREAD

**Issue by icaraps** [hlxsites/zeiss#1]
<img width="1440" alt="Screen Shot 2022-11-28 at 10 22 13 AM" src="https://user-images.githubusercontent.com/6012307/204240607-49709e06-4292-4f7a-91eb-31becfe64367.png">

**Comment by icaraps** [comment]
<img width="552" alt="Screen Shot 2022-12-01 at 5 12 34 PM" src="https://user-images.githubusercontent.com/6012307/205103270-6b58d94b-bbac-40a8-9ff8-49534f2a4104.png">

Megamenu drilldown on mobile not implemented yet

**Comment by sdmcraft** [comment]
Addressed via #45
