### ISSUE TITLE
Ensure cards get equally sized

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#114]
Reference page https://main--zeiss--hlxsites.hlx.page/drafts/satyam/sample-template

![image](https://user-images.githubusercontent.com/1191451/232748708-c1e4ba62-d8d1-4a9f-b9d4-1f439856e569.png)

**Comment by bosschaert** [comment]
@sdmcraft https://main--zeiss--hlxsites.hlx.page/drafts/satyam/sample-template contains only grey boxes, no images. Is there another page where the problem can be observed?
<img width="736" alt="Screenshot 2023-04-28 at 14 11 35" src="https://user-images.githubusercontent.com/226514/235156835-c254bca6-c98b-445e-b21a-52a500ad86d1.png">
