### ISSUE TITLE
alt-text and alt-description specified on images should appear in markup

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#115]
alt-text and alt-description specified on images in the word doc should should appear in the markup of the page generated for that word doc.

**Comment by tmaret** [comment]
@sdmcraft do you mean the `alt` resp. `title` attributes are missing in images and should be populated from content?

**Comment by sdmcraft** [comment]
@tmaret , I see a difference between the `alt` that we have on this page from the original:
https://www.zeiss.de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet.html
https://main--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet
Not sure if I am missing something here.

While the original seems to be fetching from the text in the `hero` block, we are picking from the text specified with the carousal image. We can check about what's the expectation here as in is there a set of rules behind what becomes the images alt-text. If yes, we can implement those rules else the simplest option is to let the authors specify the `alt-text` on the image itself and we just use that.

**Comment by tmaret** [comment]
@sdmcraft https://github.com/adobe/helix-md2docx/issues/255 has been fixed meanwhile and should enable us to provide the same `alt` attribute.

**Comment by tmaret** [comment]
Ah, also my changes got reverted with this commit https://github.com/hlxsites/zeiss/commit/25fe786b9e306ea30b88feef165958316edc7611

**Comment by tmaret** [comment]
Support for `title` attribute requires https://github.com/adobe/helix-html-pipeline/issues/308
