### ISSUE TITLE
Remove dark area at the right end of nav drop down menu

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#150]
![image](https://user-images.githubusercontent.com/1191451/233964508-85c8f4b6-8562-4901-969d-5f06ab518a03.png)

**Comment by jindaliiita** [comment]
Can u please mention url here as i am not able to replicate it ?

**Comment by sdmcraft** [comment]
> @sdmcraft Can u please mention url here as i am not able to replicate it ?

https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/spie-award

**Comment by jindaliiita** [comment]
https://user-images.githubusercontent.com/12638407/234064269-1064ecdb-b1fb-4f8b-9dee-52ae864cbcb2.mov

Tried on different screens, it's not reproducible. So, closing this issue
