### ISSUE TITLE
Header links are missing

### ISSUE THREAD

**Issue by bosschaert** [hlxsites/zeiss#158]
current:
https://main--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/anniversary-50-years-smt

<img width="1666" alt="Screenshot 2023-04-24 at 16 33 58" src="https://user-images.githubusercontent.com/226514/234045378-5bc66a94-260e-4262-b68f-826d82b33551.png">

expected: 
https://www.zeiss.com/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/anniversary-50-years-smt.html

<img width="1568" alt="Screenshot 2023-04-24 at 16 33 38" src="https://user-images.githubusercontent.com/226514/234045346-fc7f52be-8fcb-4861-8d88-b8c4df35a09b.png">

**Comment by jindaliiita** [comment]
@bosschaert Its visible. It takes some time to load initially, other than that it's working fine.

**Comment by sdmcraft** [comment]
And you need to disable CORS enforcement in browser.

**Comment by bosschaert** [comment]
Ah OK - didn't realise we had to disable CORS here now. Thanks for explaining! Closing the issue.
