### ISSUE TITLE
Accordion not correct in mobile view

### ISSUE THREAD

**Issue by bosschaert** [hlxsites/zeiss#192]
The accordion with links at the bottom should be collapsed in the mobile view (I looked at the iPhone SE view). 

This applies to both the parts above 'ZEISS Bereich wählen' as well as the link in the black box at the bottom 'RECHTLICHES'.

Current:
https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/ausgezeichnete-ausbildung-bei-zeiss

<img width="383" alt="Screenshot 2023-04-28 at 08 38 33" src="https://user-images.githubusercontent.com/226514/235085556-da6f907f-5445-4949-8449-6698c5112cef.png">

Expected:
https://www.zeiss.de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/ausgezeichnete-ausbildung-bei-zeiss.html

<img width="382" alt="Screenshot 2023-04-28 at 08 38 21" src="https://user-images.githubusercontent.com/226514/235085608-fa633000-c86c-4c49-82a1-25477b098520.png">

**Comment by jindaliiita** [comment]
@bosschaert Closing this issue as the changes will be covered by following issue
https://github.com/hlxsites/zeiss/issues/169
