### ISSUE TITLE
Missing carousel control in mobile view

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#214]
Test page: https://main--zeiss--hlxsites.hlx.page/drafts/satyam/sample-template

The carousel control buttons are missing. They stat appearing after the picture inside the carousel is clicked once. This happens only in the mobile view.
<img width="718" alt="image" src="https://github.com/hlxsites/zeiss/assets/1191451/c9112cc7-b450-40df-b586-81a37a168bfb">

**Comment by jindaliiita** [comment]
@sdmcraft The behavior is the same as the actual Zeiss website.
This only occurs when you are using the browser's device templates. It works fine when you actually minimize the screen. Therefore, I'm not sure if we can close it or not.

**Comment by jindaliiita** [comment]
@sdmcraft Let me know if we can close this ??

**Comment by sdmcraft** [comment]
Makes sense. Closed.

**Comment by sdmcraft** [comment]
Makes sense. Closed.
