### ISSUE TITLE
Fix importer to omit GTM iframe

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#235]
Currently all imported docs have this `iframe` tag present in the imported docs. The `iframe` tags should be omitted.

![image](https://github.com/hlxsites/zeiss/assets/1191451/0e66e1c4-26ef-4444-b864-acc752c16cd7)

**Comment by tmaret** [comment]
@sdmcraft opened https://github.com/hlxsites/zeiss/pull/237

I'll re-import all the content once it is merged.

**Comment by tmaret** [comment]
@sdmcraft found https://github.com/hlxsites/zeiss/issues/239 when importing the content

**Comment by tmaret** [comment]
Previewed and Published all pages.
