### ISSUE TITLE
Importer omits alt and title attributes on the image

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#236]
The current importer script omits `alt` and `title` attributes on the image. For e.g. on a [page like this](https://www.zeiss.de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/spie-award.html), we have images that have both `alt` and `title` attributes on the images but in the imported word doc, these are not present.

**Comment by tmaret** [comment]
Requires https://github.com/adobe/helix-html-pipeline/pull/312
