### ISSUE TITLE
Parent Page

### ISSUE THREAD

**Issue by trieloff** [hlxsites/zeiss#31]
Also port this page: https://www.zeiss.de/semiconductor-manufacturing-technology/news-und-events.html and generate article list from index.

**Comment by trieloff** [comment]
Content: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/doc2.aspx?sourcedoc=%7B83147B4B-3A11-4B8C-9F90-DBD0C07E3C68%7D&file=index.docx&action=default&mobileredirect=true

**Comment by sdmcraft** [comment]
A per [scope definition from Zeiss](https://adobe-dx-support.slack.com/archives/C04B0V6300N/p1679386308934499), the parent page would stay in AEM.
