### ISSUE TITLE
Subheadline gets pulled in from first h3

### ISSUE THREAD

**Issue by trieloff** [hlxsites/zeiss#37]
Should only get pulled from first h3 after a h1, see this page https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-expandiert-in-wetzlar-weiteres-werk-im-dillfeld

**Comment by sdmcraft** [comment]
> Should only get pulled from first h3 after a h1, see this page https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-expandiert-in-wetzlar-weiteres-werk-im-dillfeld

@trieloff , probably it should be pulled from the first h3 following and h1 _in the same section_ .  I am assuming hero block gets a section of it own. This should prevent situations of detecting false subheadings where none exist. For e.g. see https://www.zeiss.com//semiconductor-manufacturing-technology/news-and-events/smt-press-releases/anniversary-50-years-smt.html. This page has no subheading at all. wdyt?

**Comment by sdmcraft** [comment]
Closing this as the required behavior has been [implemented here](https://github.com/hlxsites/zeiss/blob/391e3046da4f24b531ec027f5acff8927eaf1580/blocks/hero/hero.js#L74-L80).
