### ISSUE TITLE
Simplify TOC block markup

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#44]
TOC block provides in page navigation as seen in https://www.zeiss.de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/quality-supplier-award-en-only.html#pressphotos

https://user-images.githubusercontent.com/1191451/222971189-a89722ed-bd47-4499-84c7-16ee9f90b3e0.mov

This task is logged to simplify its markup at https://github.com/hlxsites/zeiss/blob/b61a426d949efe128cb53fc54522df7a8a1568cc/blocks/toc/toc.js#L5-L65

**Comment by sdmcraft** [comment]
If we find that TOC block is no longer needed (as being discussed in #166), I think we can just remove this block altogether.

**Comment by tmaret** [comment]
No (current) content is using the TOC block. Closing.
