### ISSUE TITLE
Fetch Nav from AEM and render it in Franklin pages

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#45]
As seen in https://www.zeiss.de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/europaeischer-erfinderpreis-2018.html
![image](https://user-images.githubusercontent.com/1191451/222971311-ea695c9a-9b77-4672-accf-4240d1094ea8.png)

**Comment by tmaret** [comment]
@sdmcraft what URL should we fetch the nav content from ?

**Comment by tmaret** [comment]
Found https://www.zeiss.com/semiconductor-manufacturing-technology/home.html which could serve as basis
