### ISSUE TITLE
Fetch Footer from AEM and render it in Franklin pages

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#46]
As seen in https://www.zeiss.de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/europaeischer-erfinderpreis-2018.html

![image](https://user-images.githubusercontent.com/1191451/222971428-33603612-c184-4a9a-a0b7-03469bdb2524.png)

**Comment by tmaret** [comment]
@sdmcraft what URL should we fetch the footer content from ?

**Comment by tmaret** [comment]
Found https://www.zeiss.com/semiconductor-manufacturing-technology/home.html which could serve as basis

**Comment by tmaret** [comment]
@sdmcraft to fetch the page, we'd need the server (AEM) serving the page https://www.zeiss.com/semiconductor-manufacturing-technology/home.html to emit `Access-Control-Allow-Origin` response header to allow Helix to fetch the content.
