### ISSUE TITLE
Simplify Collapsible text block markup

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#47]
As seen in https://www.zeiss.de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/ausgezeichnete-ausbildung-bei-zeiss.html

https://user-images.githubusercontent.com/1191451/222971663-7fd7607f-6ab5-4e93-b804-cc1d558632c1.mov

This is currently implemented as the `collapse` block at https://github.com/hlxsites/zeiss/blob/b61a426d949efe128cb53fc54522df7a8a1568cc/blocks/collapse/collapse.js. 

The markup can be simplified. Currently it is as follows https://github.com/hlxsites/zeiss/blob/b61a426d949efe128cb53fc54522df7a8a1568cc/blocks/collapse/collapse.js#L5-L50

**Comment by sdmcraft** [comment]
@alinarublea , I think the only thing remaining open here is the update to the `collapse` block across word docs which we can do via the `Franklin Import` route. Would you be taking it up under this issue or separately?

**Comment by alinarublea** [comment]
I can take it as part of this issue
