### ISSUE TITLE
Simplify "Contact" block's markup

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#49]
As seen in https://www.zeiss.de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/europaeischer-erfinderpreis-2018.html#presseinformation

![image](https://user-images.githubusercontent.com/1191451/222971976-3d5dc1fd-8a50-48cd-ae38-1a8c089c4dd5.png)

This is handeled by the "Contact" block. This task is logged to simplify the markup generated by this block here
https://github.com/hlxsites/zeiss/blob/b61a426d949efe128cb53fc54522df7a8a1568cc/blocks/contact/contact.js#L5-L74

**Comment by tmaret** [comment]
Example article with multiple contacts https://www.zeiss.de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/deutscher-zukunftspreis-2020-euv.html
