### ISSUE TITLE
Fix Download (columns) block

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#61]
2 problems to fix:

1. The text below the image is missing.
2. The items are not styled correctly,

![image](https://user-images.githubusercontent.com/1191451/226112759-cc1ada82-833a-4dbf-acf4-6306dc11994f.png)

Expected https://www.zeiss.de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/spie-award.html

![image](https://user-images.githubusercontent.com/1191451/226112788-f415e89c-7301-4b30-9fa2-de8d4d6b1f61.png)

Current https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/spie-award

![image](https://user-images.githubusercontent.com/1191451/226112921-1ab74c6d-09bd-42cb-ac29-6f6aa762d81c.png)

**Comment by sdmcraft** [comment]
I think this is partially addressed already via #141 by @tmaret . The part remaining here is the styling part of the download link etc.

**Comment by tmaret** [comment]
@alinarublea are you fine if I handle the styling part ?

**Comment by sdmcraft** [comment]
@alinarublea , can we mark this as closed? I think you took care of this in https://github.com/hlxsites/zeiss/commit/1aaa286a56e1f0eea713ca171e6c946119beea82 .
