### ISSUE TITLE
Setup GTM

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#64]

**Comment by tmaret** [comment]
GTM integration on the current site consists of two pieces of JS code inlined in the document head tag. Conceptually we could copy paste that code in the new site. 

Any recommendation if the script should be inlined or referenced ?

**Comment by sdmcraft** [comment]
> GTM integration on the current site consists of two pieces of JS code inlined in the document head tag. Conceptually we could copy paste that code in the new site.
> 
> Any recommendation if the script should be inlined or referenced ?

Typically the GTM code goes in `delayed.js`. You can see [examples here](https://github.com/search?q=org%3Ahlxsites+gtm&type=code)

**Comment by tmaret** [comment]
Tracked https://github.com/hlxsites/zeiss/issues/87 for user data management
