### ISSUE TITLE
Search function in navbar

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#68]
![image](https://user-images.githubusercontent.com/1191451/226833917-115dd8ca-8b00-449a-abea-09163a4fd4c7.png)

![image](https://user-images.githubusercontent.com/1191451/226833968-6a5713fe-1c08-40af-b692-b7eb476e22af.png)

**Comment by tmaret** [comment]
@sdmcraft is there a documentation that cover setting this up ? Does it depend on #50 ?
