### ISSUE TITLE
Add backwards navigation link

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#71]
![image](https://user-images.githubusercontent.com/1191451/228485864-23a74437-188d-448f-b858-abf357943c2e.png)

**Comment by bosschaert** [comment]
The change should also include adding the horizontal line.

**Comment by sdmcraft** [comment]
@bosschaert , I think a few more thing to be addressed here

![image](https://user-images.githubusercontent.com/1191451/231985399-fff1ea14-ecf5-4105-aef6-d027004a33d9.png)

**Comment by bosschaert** [comment]
Hi @sdmcraft yes thanks correct I'm working on that. Maybe this issue was auto-closed by my merge.
