### ISSUE TITLE
Fix date format

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#72]
![image](https://user-images.githubusercontent.com/1191451/228486258-e444b49b-cd6d-41a4-a4c3-c2f5a8cc1b2a.png)

**Comment by RitwikSrivastava** [comment]
@sdmcraft Do we want the date format in this format "WED NOV 25 2020 " or  just
"25 November 2020" ?

**Comment by sdmcraft** [comment]
> @sdmcraft Do we want the date format in this format "WED NOV 25 2020 " or just "25 November 2020" ?

It should be like "28. FEBRUAR 2023 " . [See this page for reference.](https://www.zeiss.de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/spie-award.html)
