### ISSUE TITLE
Improve placeholders handling

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#97]
[Related slack discussion.](https://cq-dev.slack.com/archives/C04RN3CQWBZ/p1681286749300359?thread_ts=1681285325.872289&cid=C04RN3CQWBZ)

**Comment by jindaliiita** [comment]
Points to cater
1. Make a single placeholder file that will take care of all the languages.
2. Change **fetchPlaceholders** function to handle the above scenario.

@sdmcraft, @tmaret AFAIU we need to cater above two points here.
Do we need to include any additional text in the placeholder sheet, apart from what is already present in the different sheets ?
